name = "chasse1"
compatibility_date = "2025-12-07"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "chasse-db"
database_id = "dcbaf1d3-218b-4260-bd9e-3f60d3139f29"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "chasse-uploads"
